server.port=8083

spring.datasource.url=jdbc:h2:mem:transactiondb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.application.name=transaction-service

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
info.app.name=Transaction Service
info.app.version=1.0.0
info.app.description=NovaBankApp Transaction Service

# Show all SQL logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Show Spring logs
logging.level.com.novabank=DEBUG

# Show web request logs
logging.level.web=DEBUG