server.port=8083
spring.application.name=transaction-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/novabank
spring.datasource.username=postgres
spring.datasource.password=Vinod@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# App info
info.app.name=Transaction Service
info.app.version=1.0.0
info.app.description=NovaBankApp Transaction Service

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.novabank=DEBUG