server.port=8081
spring.application.name=auth-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/novabank
spring.datasource.username=postgres
spring.datasource.password=Vinod@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=novabankSuperSecretKey123456789012345
jwt.expiration=86400000

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.security.enabled=false

# App info
info.app.name=Authentication Service
info.app.version=1.0.0
info.app.description=NovaBankApp Authentication Service

# Security
spring.security.user.name=user
spring.security.user.password=novabank123

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.novabank=DEBUG